version: '2.4'

services:

  reditr:
    image: "talmai/reditr"
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - '3000'
    ports:
        - '3000:3000'
    container_name: reditr
